In [1]:
print("Meu primeiro notebook de Data Science!")

Meu primeiro notebook de Data Science!

In [2]:
import pandas as pd

In [2]:
import pandas as pd
print(pd.__version__)

3.1.0

In [3]:
dados = {
    "cliente": ["Ana", "Carlos", "Pedro"],
    "valor": [150, 2500, 80],
    "tipo": ["Pix", "Cartão", "Pix"]
}

df = pd.DataFrame(dados)

df

  cliente  valor    tipo
0     Ana    150     Pix
1  Carlos   2500  Cartão
2   Pedro     80     Pix

In [4]:
dados = {
    "Cliente": ["Ana", "João", "Clara"]
    }

df = pd.DataFrame(dados)

df

  Cliente
0     Ana
1    João
2   Clara

In [5]:
df ["Cliente"]

0      Ana
1     João
2    Clara
Name: Cliente, dtype: str

In [10]:
df.loc[1, ["Cliente"]]

Cliente    João
Name: 1, dtype: str

In [16]:
df.loc[[0,2],["Cliente"]]

  Cliente
0     Ana
2   Clara

In [17]:
df.loc["João" == df["Cliente"]]

  Cliente
1    João